<?php

declare(strict_types=1);

namespace Atria\Database\Schema\Grammars;

use Atria\Database\Schema\ColumnDefinition;

class PgSqlSchemaGrammar extends SchemaGrammar
{
    protected function type(ColumnDefinition $column): string
    {
        return match ($column->type) {
            'id' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            'integer' => 'INTEGER',
            'bigInteger', 'foreignId' => 'BIGINT',
            'string' => $this->varcharType($column),
            'text' => 'TEXT',
            'boolean' => 'BOOLEAN',
            'decimal' => $this->decimalType($column),
            'date' => 'DATE',
            'timestamp' => 'TIMESTAMP',
            'json' => 'JSONB',
            default => throw new \InvalidArgumentException("Unsupported column type: {$column->type}"),
        };
    }

    protected function booleanLiteral(bool $value): string
    {
        return $value ? 'TRUE' : 'FALSE';
    }
}
