<?php

declare(strict_types=1);

namespace Atria\Database\Contracts;

use Atria\Database\Result;

/**
 * One physical database connection managed by a PooledConnection.
 *
 * Implementations wait for the server through the Atria\Async event loop, so
 * a query suspends the current Async::run() task instead of blocking the thread
 * whenever the driver supports it.
 */
interface ConnectionLink
{
    /**
     * @param array<int, mixed> $bindings Positional values for `?` placeholders.
     */
    public function query(string $sql, array $bindings): Result;

    public function begin(): void;

    public function commit(): void;

    public function rollback(): void;

    /**
     * Id generated by the last INSERT on this connection, or null when unavailable.
     */
    public function lastInsertId(): ?string;

    /**
     * Whether the connection is usable: not lost and not left mid-query.
     */
    public function isHealthy(): bool;

    /**
     * Whether the connection is outside any transaction.
     */
    public function isIdle(): bool;

    /**
     * Rolls back synchronously, outside the event loop; used between requests.
     *
     * @return bool false when the connection is mid-query or the rollback failed.
     */
    public function rollbackBlocking(): bool;

    public function close(): void;

    /**
     * Unix time at which the connection was opened.
     */
    public function connectedAt(): int;
}
