<?php

declare(strict_types=1);

namespace Atria\Database\Contracts;

use PDOStatement;

interface DatabaseConnection
{
    public function connect(): void;

    public function disconnect(): void;

    public function getConnection(): mixed;

    public function beginTransaction(): void;

    public function isConnected(): bool;

    public function commit(): void;

    public function rollback(): void;

    public function inTransaction(): bool;

    /**
     * Returns the id generated by the last INSERT, or null when unavailable.
     */
    public function lastInsertId(): ?string;

    /**
     * @param array<int,mixed> $bindings
     * @return PDOStatement|bool
     */
    public function execute(string $query, array $bindings): PDOStatement|bool;
}
