<?php

declare(strict_types=1);

use Atria\Database\Schema\Blueprint;
use Atria\Database\Schema\Grammars\MySqlSchemaGrammar;
use Atria\Database\Schema\Grammars\PgSqlSchemaGrammar;
use Atria\Database\Schema\Grammars\SchemaGrammar;
use Atria\Database\Schema\Grammars\SqliteSchemaGrammar;
use Atria\Database\Schema\Schema;

function postsBlueprint(): Blueprint
{
    $table = new Blueprint('posts');
    $table->id();
    $table->foreignId('user_id')->references('users')->cascadeOnDelete();
    $table->string('title', 120);
    $table->text('body')->nullable();
    $table->boolean('published')->default(true);
    $table->decimal('price', 10, 2)->default(0);
    $table->json('meta')->nullable();
    $table->timestamps();
    $table->index(['user_id']);
    $table->unique(['user_id', 'title'], 'posts_owner_title');

    return $table;
}

test('pgsql grammar compiles table and separate indexes', function () {
    expect(new PgSqlSchemaGrammar()->compileCreate(postsBlueprint()))->toBe([
        'CREATE TABLE IF NOT EXISTS posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
        . 'user_id BIGINT NOT NULL, title VARCHAR(120) NOT NULL, body TEXT NULL, '
        . 'published BOOLEAN NOT NULL DEFAULT TRUE, price DECIMAL(10, 2) NOT NULL DEFAULT 0, meta JSONB NULL, '
        . 'created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL, '
        . 'FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)',
        'CREATE INDEX IF NOT EXISTS posts_user_id_index ON posts (user_id)',
        'CREATE UNIQUE INDEX IF NOT EXISTS posts_owner_title ON posts (user_id, title)',
    ]);
});

test('sqlite grammar compiles table and separate indexes', function () {
    expect(new SqliteSchemaGrammar()->compileCreate(postsBlueprint()))->toBe([
        'CREATE TABLE IF NOT EXISTS posts (id INTEGER PRIMARY KEY AUTOINCREMENT, '
        . 'user_id INTEGER NOT NULL, title VARCHAR(120) NOT NULL, body TEXT NULL, '
        . 'published INTEGER NOT NULL DEFAULT 1, price DECIMAL(10, 2) NOT NULL DEFAULT 0, meta TEXT NULL, '
        . 'created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NULL, '
        . 'FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)',
        'CREATE INDEX IF NOT EXISTS posts_user_id_index ON posts (user_id)',
        'CREATE UNIQUE INDEX IF NOT EXISTS posts_owner_title ON posts (user_id, title)',
    ]);
});

test('mysql grammar declares indexes inside a single CREATE TABLE', function () {
    expect(new MySqlSchemaGrammar()->compileCreate(postsBlueprint()))->toBe([
        'CREATE TABLE IF NOT EXISTS posts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, '
        . 'user_id BIGINT UNSIGNED NOT NULL, title VARCHAR(120) NOT NULL, body TEXT NULL, '
        . 'published TINYINT(1) NOT NULL DEFAULT 1, price DECIMAL(10, 2) NOT NULL DEFAULT 0, meta JSON NULL, '
        . 'created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NULL, '
        . 'FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, '
        . 'INDEX posts_user_id_index (user_id), UNIQUE INDEX posts_owner_title (user_id, title)) '
        . 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
    ]);
});

test('string defaults are quoted and escaped', function (SchemaGrammar $grammar) {
    $table = new Blueprint('settings');
    $table->string('label')->default("it's");
    $table->foreignId('owner_id')->nullable()->references('users')->nullOnDelete();

    expect($grammar->compileCreate($table)[0])
        ->toContain("label VARCHAR(255) NOT NULL DEFAULT 'it''s'")
        ->toContain('owner_id')
        ->toContain('REFERENCES users(id) ON DELETE SET NULL');
})->with([
    'pgsql' => fn() => new PgSqlSchemaGrammar(),
    'sqlite' => fn() => new SqliteSchemaGrammar(),
    'mysql' => fn() => new MySqlSchemaGrammar(),
]);

test('drop compiles DROP TABLE IF EXISTS', function () {
    expect(new PgSqlSchemaGrammar()->compileDrop('posts'))->toBe('DROP TABLE IF EXISTS posts');
});

test('schema executes every compiled statement on the connection', function () {
    $connection = new MockDatabaseConnection();
    $schema = new Schema($connection, new PgSqlSchemaGrammar());

    $schema->create('posts', static function (Blueprint $table): void {
        $table->id();
        $table->index(['id']);
    });
    $schema->drop('posts');

    expect($connection->executedQueries)->toBe([
        'CREATE TABLE IF NOT EXISTS posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)',
        'CREATE INDEX IF NOT EXISTS posts_id_index ON posts (id)',
        'DROP TABLE IF EXISTS posts',
    ]);
});
